package in.pervush.poker.model;

public enum ErrorStatus {
    INVALID_USER_NAME,
    INVALID_USER_EMAIL,
    USER_EMAIL_EXISTS,
    TOO_WEAK_USER_PASSWORD,
    INVALID_TASK_NAME,
    INVALID_TASK_URL,
    TASK_URL_EXISTS,
    INVALID_TASK_STATUS,
    INVALID_VOTE_VALUE,
    INVALID_TEAM_NAME,
    USER_ALREADY_ADDED,
    USER_EMAIL_NOT_EXISTS
}
